In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df_train = pd.read_csv('datasets/mnist_train.csv')
df_train.head(3)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df_test = pd.read_csv('datasets/mnist_test.csv')
df_test.head(3)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
X_train = df_train.iloc[:, 1:].values
X_test = df_test.iloc[:, 1:].values
y_train = df_train.iloc[:, 0].values
y_test = df_test.iloc[:, 0].values

In [6]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.fit_transform(X_test)

In [7]:
from sklearn.neural_network import MLPClassifier
def fitAndTest(X_train, X_test, y_train, y_test):
    model = MLPClassifier(random_state=0)
    model.fit(X_train, y_train)
    accuracy = model.score(X_train, y_train)
    print('Training score: {:.3f}'.format(accuracy))
    accuracy = model.score(X_test, y_test)
    print('Testing score: {:.3f}'.format(accuracy))

In [8]:
print('Before scaling: ')
fitAndTest(X_train, X_test, y_train, y_test)

Before scaling:
Training score: 0.993
Testing score: 0.965

In [9]:
print('After scaling: ')
fitAndTest(X_train_scaled, X_test_scaled, y_train, y_test)

After scaling:
Training score: 1.000
Testing score: 0.974

In [10]:
from sklearn.decomposition import PCA
pac = PCA(n_components=10)

pComponent = pac.fit_transform(X_train_scaled)
pDF = pd.DataFrame(data=pComponent, columns=['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'])
df_train_2 = pd.concat([pDF,df_train['label']], axis=1)
df_train_2

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,label
0,-0.922159,-4.814804,0.067569,-8.051100,-0.986263,0.953265,0.333661,1.406484,1.046181,2.255988,5
1,8.708984,-7.754417,-3.447866,-1.668748,0.836847,-5.149588,-0.274847,3.108254,0.147040,-1.322425,0
2,2.328396,9.431347,-6.183956,1.724219,4.094786,2.287467,18.707032,3.972702,-2.202356,-0.401281,4
3,-6.582170,-3.746333,3.690912,-0.461201,5.626317,3.459853,1.562612,-4.601003,0.619593,-2.660425,1
4,-5.183240,3.133252,-6.277816,1.459409,-1.608408,-0.616580,-0.580035,-3.214213,-0.049726,-0.833117,9
...,...,...,...,...,...,...,...,...,...,...,...
59995,-2.039336,-5.119110,0.375269,-4.688517,-0.643368,2.897688,-0.223852,-3.690562,1.547455,0.003874,8
59996,0.607838,-6.498438,3.507226,-8.397454,-1.008084,1.240346,3.965943,0.912221,7.236123,1.167647,3
59997,-3.777208,-3.230574,-3.806087,-7.503871,-1.362522,-2.877951,1.703454,-2.461668,-2.712103,4.376290,5
59998,1.722362,-4.948142,0.006792,7.151376,-0.926062,-5.062826,3.641411,3.817615,-2.740075,-0.395091,6
59999,-1.427250,-6.175376,-2.967728,-0.392290,3.499651,2.795119,-0.356405,-2.042836,-3.694939,2.399042,8

In [11]:
pComponent = pac.fit_transform(X_test_scaled)
pDF = pd.DataFrame(data=pComponent, columns=['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'])
df_test_2 = pd.concat([pDF, df_test['label']], axis=1)
df_test_2

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,label
0,-5.458317,6.413965,-4.199385,-0.332697,3.324279,2.400757,-2.810905,8.065810,-3.793762,-2.599239,7
1,2.804439,-8.028921,16.185961,4.334689,0.956690,2.294829,-3.196768,5.124961,5.241723,-3.391430,2
2,-7.411242,-3.864042,1.089609,3.920985,6.184844,-2.487493,1.621970,-0.999644,-0.684939,-0.379321,1
3,8.751248,0.046010,-2.851207,-0.199144,-5.993165,-4.908761,-2.448473,6.937025,-0.272202,-0.206630,0
4,-0.065755,6.296269,-0.396528,2.681919,-2.087816,0.427973,3.681335,-4.460585,-4.411578,-4.902158,4
...,...,...,...,...,...,...,...,...,...,...,...
9995,3.579476,-3.367947,10.179961,-1.303104,-0.434727,11.223635,-5.485504,1.934235,-3.732575,1.543220,2
9996,3.244813,-1.981761,8.603927,-7.362262,-1.075608,-2.881294,-1.054870,6.670435,-2.560574,0.027484,3
9997,-5.004357,1.153647,-5.017135,0.201935,-4.494462,4.819461,-4.568723,-0.452658,1.465733,-1.287726,4
9998,-1.420847,-4.423176,-7.007068,2.260880,4.673185,-1.730403,-3.318697,1.769763,9.877650,-0.954113,5
9999,13.142676,-4.262850,-1.146251,10.800057,-8.402924,-5.126649,2.132951,3.079981,5.529307,6.511237,6

In [12]:
X_train_2 = df_train_2.iloc[:, :-1].values
X_test_2 = df_test_2.iloc[:, :-1].values
y_train_2 = df_train_2.iloc[:, -1].values
y_test_2 = df_test_2.iloc[:, -1].values

In [14]:
X_train_2_scaled = sc.fit_transform(df_train_2)
X_test_2_scaled = sc.fit_transform(df_test_2)

fitAndTest(X_train_2_scaled, X_test_2_scaled, y_train_2, y_test_2)

Training score: 1.000
Testing score: 0.992